# Generated by Django 3.2.6 on 2021-12-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=250)),
                ('video', models.FileField(upload_to='./static_cache/sent_vid/', verbose_name='Video')),
            ],
        ),
    ]
